cart/urls.py
from django.urls import path

from cart import views

app_name = 'cart'

urlpatterns = [
    path('order/', views.view_order, name='order'),
    path('add/', views.add_to_cart, name='add_to_cart',),
    path('', views.view_cart, name='cart',),
]

config/urls.py
import debug_toolbar

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from article import views

urlpatterns = [
    path('catalog/', include(('catalog.urls', 'catalog'), namespace='catalog')),
    path('cart/', include('cart.urls')),
    path('account/', include('account.urls')),
    path('admin/', admin.site.urls),
    path('', views.view_home, name='home')
] + static(
    settings.STATIC_URL, document_root=settings.STATIC_ROOT
) + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

urlpatterns += staticfiles_urlpatterns()

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" >
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>{% block title %}{% endblock %}</title>
  <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'main.css' %}">
</head>
<body class="" data-gr-c-s-loaded="true">

{% include 'menu.html' %}

{% block content %}{% endblock %}

<hr>

{% include 'footer.html' %}

<script src="{% static 'jquery-3.3.1.slim.min.js' %}"></script>
<script src="{% static 'popper.min.js' %}"></script>
<script src="{% static 'bootstrap.min.js' %}"></script>
</body>
</html>

templates/footer.html
<footer class="container">
  <p>© Просто магазин 2021</p>
</footer>

templates/index.html
{% extends 'base.html' %}

{% block title %}Главная{% endblock %}

{% block content %}

     <main role="main">
        {% for article in articles %}
            <div>
                <div class="jumbotron">
                    <div class="container">
                        <h1 class="display-4"> {{ article.name }} </h1>
                        <p> {{ article.text }} </p>
                    </div>
                </div>
                <div class="container mb-5">
                    <div class="row">
                        {% for product in article.products.all %}
                            <div class="col-md-4">
                                <h2>{{ product.title }}</h2>
                                <a href="{{ product.get_absolute_url }}">
                                    <img src="{{ product.image.url }}" width="120">
                                </a>
                                <p>{{ product.description }}</p>
                                {% include 'cart/add_to_cart.html' %}
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </main>
{% endblock %}

templates/menu.html
{% load static %}
{% load catalog_extras %}

<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <a class="navbar-brand" href="{% url 'home' %}">Просто магазин</a>
  <img src="{% static 'logo.svg' %}" alt="" width="42" height="42">
  <button class="navbar-toggler" type="button" data-toggle="collapse"
          data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault"
          aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'home' %}">
          Главная
        </a>
      </li>
        {% include 'catalog/catalog_menu.html' %}
    </ul>



    {% if user.is_authenticated %}
        <div class="text-success">Пользователь: {{ user.get_username }}</div>
    {% endif %}

    <a class="btn btn-outline-success my-2 my-sm-0" role="button" href="{% url 'cart:cart' %}">Корзина</a>

    {% if user.is_authenticated %}
        <a class="btn btn-outline-success my-2 my-sm-0" role="button" href="{% url 'logout'%}?next={{request.path}}">Выйти</a>
    {% else %}
        <a class="btn btn-outline-success my-2 my-sm-0" role="button" href="{% url 'login'%}?next={{request.path}}">Войти</a>
    {% endif %}



  </div>
</nav>